### ISSUE TITLE
[Carthage] ObjectMapper fails to build on XCODE 12.0 beta 4 (12A8179i)

### ISSUE THREAD

**Issue by SudhirGadhvi** [tristanhimmelman/ObjectMapper#1105]
**Describe the bug**

ObjectMapper fails to build on  XCODE 12.0 beta 4 (12A8179i)

```
Build Failed
	Task failed with exit code 1:
/usr/bin/xcrun lipo -create /Users/Sudhir/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/ObjectMapper/3.5.3/Build/Intermediates.noindex/ArchiveIntermediates/ObjectMapper-iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/ObjectMapper.framework/ObjectMapper /Users/Sudhir/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A8179i/ObjectMapper/3.5.3/Build/Products/Release-iphonesimulator/ObjectMapper.framework/ObjectMapper -output /Users/Sudhir/Documents/S!D/Projects/RosterBuster-iOS/Carthage/Build/iOS/ObjectMapper.framework/ObjectMapper
```

**Reproduce**
Steps to reproduce:

1. Delete derived Carthage Cache.
2. Delete Carthage directory in project.
3. Uninstall Carthage and install it again.
4. `xcode-select --switch` to choose the Xcode 12 beta
5. Remove `/Library/Caches/org.carthage.CarthageKit/DerivedData/`
6. `carthage update --platform iOS --no-use-binaries`

**Comment by perlasivakrishna** [comment]
I'm using cocoapods, it fails to build for that too

**Comment by elliotPopina** [comment]
Hello, it's not a ObjectMapper, it's a Carthage problem, see [https://github.com/Carthage/Carthage/issues/3019](url)

**Comment by frandelarosa** [comment]
I'm struggling into this too. Any workaround to fix it?

**Comment by frandelarosa** [comment]
> Hello, it's not a ObjectMapper, it's a Carthage problem, see [https://github.com/Carthage/Carthage/issues/3019](url)

I think it's a ObjectMapper problem, I tried with both of them and can't compile.

**Comment by elliotPopina** [comment]
I have success to build ObjectMapper, with this script for Carthage

`#!/usr/bin/env bash

# carthage-build.sh
# Usage example: ./carthage-build.sh --platform iOS

set -euo pipefail

xcconfig=$(mktemp /tmp/static.xcconfig.XXXXXX)
trap 'rm -f "$xcconfig"' INT TERM HUP EXIT

# For Xcode 12 make sure EXCLUDED_ARCHS is set to arm architectures otherwise
# the build will fail on lipo due to duplicate architectures.
# Xcode 12 Beta 3:
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8169g = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 beta 4
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8179i = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 beta 5
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8189h = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 beta 6
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A8189n = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 GM (12A7208)
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A7208 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig
# Xcode 12 GM (12A7209)
echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_12A7209 = arm64 arm64e armv7 armv7s armv6 armv8' >> $xcconfig

echo 'EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200 = $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64__XCODE_1200__BUILD_$(XCODE_PRODUCT_BUILD_VERSION))' >> $xcconfig
echo 'EXCLUDED_ARCHS = $(inherited) $(EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_$(EFFECTIVE_PLATFORM_SUFFIX)__NATIVE_ARCH_64_BIT_$(NATIVE_ARCH_64_BIT)__XCODE_$(XCODE_VERSION_MAJOR))' >> $xcconfig

export XCODE_XCCONFIG_FILE="$xcconfig"
carthage build "$@"`

**Comment by frandelarosa** [comment]
I've used the script mentioned above and my project has compiled successfully. Thanks @elliotPopina!
