### ISSUE TITLE
Basic type set mapping for ImmutableMappable

### ISSUE THREAD

**Issue by ManWithBear** [tristanhimmelman/ObjectMapper#661]
After quick research I found that framework not support mapping of basic type set (like Set<String>).
Mapper trying to use `public func >>> <T>(left: T, right: Map) `, but `ToJSON` class in `class func basicType<N>(_ field: N, map: Map)` don't contain Set.
Am I right?
Right now I use TransformType workaround:
```
open class SetTransform<T:Hashable>: TransformType {
	public typealias Object = Set<T>
	public typealias JSON = Array<T>

	public init() {}

	open func transformFromJSON(_ value: Any?) -> Set<T>? {
		guard let array = value as? Array<T> else {
			return nil
		}
		return Set<T>(array)
	}

	open func transformToJSON(_ value: Set<T>?) -> Array<T>? {
		guard let set = value else{
			return nil
		}
		return Array<T>(set)
	}
}
```

**Comment by KoCMoHaBTa** [comment]
I guess that there is no point to have `Set` directly, because there is no direct representation of Set in the JSON format. I think that you probably have found the best approach to use `Set`. In addition to your transform, you could use overload of the `>>>` mapping operator and introduce the `Set` by using your `SetTransform`. I believe this should be fine if you submit a PR with these changes.

**Comment by ManWithBear** [comment]
Here already implementation for Set<T: BasicMappable>, so it make sense have mapping for basic Set.
